<?php

require_once(drupal_get_path('module', 'find_cadets') .'/includes/find_cadets.inc');
/**
 * Implements hook_menu().
 */

function find_cadets_menu(){
global $user;


  $items['pilots/show-cadets'] = array(
  'title'  => t('Find Cadets to Fly'),
//  'access arguments' => array('access arguments page'),
    'access callback' => 'user_is_logged_in',  
  'page callback' => 'find_cadets_now',
);


  $items['pilots/find-cadets'] = array(
    'title' => 'Look For Cadets To Fly',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_find_cadets'),
    'access callback' => TRUE,
    'description' => 'look for cadets',
    'type' => MENU_LOCAL_TASK,
    'file' => 'find_cadets_forms.inc',
  );


  return $items;
}

function find_cadets_now(){
global $user;

$days = find_cadets_get_vals("days");
$months = find_cadets_get_vals("months");

$cadets=array();
$pilots_airport_tid = (isset($_POST['selected']) ?  $_POST['selected'] : 0);
$dateStr     = (isset($_POST['date']['date']) ? $_POST['date']['date']  : date("%a, %d-%b-%Y"));
$tmDateAry = strptime($dateStr, "%a, %d-%b-%Y");
$dateAry = array(
           'dow'   => $tmDateAry['tm_wday'] + 1,
           'day'   => $tmDateAry['tm_mday'],
           'month' => $tmDateAry['tm_mon'] + 1,
           'year'  => $tmDateAry['tm_year'] + 1900
           );
$requested_date = $dateAry['year'] . "-" . sprintf("%02d", $dateAry['month']) . "-" . sprintf("%02d", $dateAry['day']);
$requested_date_pretty = $days[$dateAry['dow']] . ", " . $dateAry['day'] . " " . $months[$dateAry['month']] . " " . $dateAry['year'];;
// Find the list of cadet submissions that match the pilot's requested date and the pilot's airport
//    SID = webform submission ID
//    CID = webform component ID
//         CID #1 => the requested date
//         CID #2 => Airport ID
//$result = db_query("SELECT DISTINCT w.sid FROM {webform_submitted_data} w WHERE
//                      (SELECT w.sid from {webform_submitted_data} w WHERE w.cid=1 AND w.data= :rdate) IN 
//                      (SELECT w.sid from {webform_submitted_data} w WHERE w.cid=2 AND w.data= :airp)", 
//                     array(':rdate' => $requested_date, ':airp' => $pilots_airport_tid));

$result = db_query("SELECT a.sid from {webform_submitted_data} a 
                    INNER JOIN {webform_submitted_data} b
                    ON a.sid=b.sid
                    WHERE (a.cid=1 AND a.data = :rdate)
                    AND   (b.cid=2 AND b.data = :airp)",
                    array(':rdate' => $requested_date, ':airp' => $pilots_airport_tid));

$cadetHtml = "";
$cadetIdx=0;
   foreach ($result as $record){
   $cadets[$cadetIdx] = build_cadet_record($record->sid, $requested_date);
   $cadetHtml .= $cadets[$cadetIdx]->html;
   $cadetIdx++;
   }

//$numCadets = count($cadets);

  if ($cadetIdx > 0){
  $h1_markup = "Cadets who are available to fly on " . $requested_date_pretty;
  $h2_prefix = "<span class='subhead'><form><div class=\"cadet_wrapper\">
                <div class=\"cadet\"><div class=\"cadet_row cadet_row_head\">Send Email</div>
                <div class=\"cadet_row cadet_row_head\">Name</div>
                <div class=\"cadet_row cadet_row_head\">CAPID</div>
                <div class=\"cadet_row cadet_row_head\">Weight</div>
                <div class=\"cadet_row cadet_row_head\">Phone</div>
                <div class=\"cadet_row cadet_row_head\">Email</div>
                <div class=\"cadet_row cadet_row_head\">Curriculum</div></div>";
  $h2_suffix = "</div></form></span><br /><br />";
  } else {
  $h1_markup = "No cadets are available to fly on " . $requested_date_pretty;
  $h2_prefix = "<span class='subhead'>";
  $h2_suffix = "</span><br /><br />";
  }

$render_array = array(
    '#show_messages' => TRUE,
//    '#type'  => 'page',
    '#title' => 'FOOOO',
  'content' => array(
   'h1' => array(
      '#markup' => $h1_markup,
      '#prefix' => "<span class='head top_padding'>",
      '#suffix' => '</span><br /><br />',
   ),


   'h2' => array(
      '#markup' => $cadetHtml,
      '#prefix' => $h2_prefix,
      '#suffix' => $h2_suffix,
   ),
  
),
);
  return($render_array);


}

function find_cadets_events_arguments($foo){
global $user;

$airport_tid = $_POST['selected'];
$dateStr     = $_POST['date']['date'];
$tmDateAry = strptime($dateStr, "%a, %d-%b-%Y");
$dateAry = array(
           'day'   => $tmDateAry['tm_mday'],
           'month' => $tmDateAry['tm_mon'] + 1,
           'year'  => $tmDateAry['tm_year'] + 1900
           );

$test1 = views_embed_view('find_cadets', 'block');
$mm = "<pre>" . print_r($test1, TRUE) . "</pre>";
watchdog('CAP', $mm);


$string = "<span class='head top_padding'>locale</span><br /><br />" .  " <br>passed  param to this page. ";
$render_array = array(
    '#show_messages' => TRUE,
//    '#type'  => 'page',
    '#title' => 'FOOOO',
  'content' => array(

   'h1' => array(
      '#markup' => t('Boosters & Events'),
      '#prefix' => "<span class='head top_padding'>",
      '#suffix' => '</span><br /><br />',
   ),


   'h2' => array(
      '#markup' => "HH",
      '#prefix' => "<span class='subhead'>",
      '#suffix' => '</span><br /><br />',
   ),

   'upcoming_title' => array(
      '#markup' => t('Upcoming Events'),
      '#prefix' => '<h4 class="event-head">',
      '#suffix' => '</h4><br />',
   ),



   'previous_title' => array(
      '#markup' => t('Previous Events'),
      '#prefix' => '<h4 class="event-head">',
      '#suffix' => '</h4><br />',
      ),


   ),
);


//  return t($string);
  return($render_array);


}


/**
 *  Form constructor for the example form.
 */
function find_cadets_form($form, &$form_state) {
  // Provide a text field.
  $form['name'] = array(
    '#title' => t('Your full name'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );
  
  // Provide a submit button.
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Update search',
  );
  
  return $form;
}



/**
 * Build one record from the matching submission data
 *  Input: Submission ID, request date (format = YYYY-mm-dd)
 *  Return: Matching record object
 */
function build_cadet_record($sid, $requested_date){

$result = db_query("SELECT field_data_field_first_name.field_first_name_value AS fname, 
       field_data_field_last_name.field_last_name_value AS lname, 
       field_data_field_capid.field_capid_value AS capid,
       field_data_field_weight.field_weight_value AS weight,
       field_data_field_phone_number.field_phone_number_value AS phone,
       mail from users LEFT JOIN webform_submissions         ON webform_submissions.uid = users.uid 
                       LEFT JOIN field_data_field_first_name ON field_data_field_first_name.entity_id = users.uid
                       LEFT JOIN field_data_field_last_name  ON field_data_field_last_name.entity_id = users.uid
                       LEFT JOIN field_data_field_capid     ON field_data_field_capid.entity_id = users.uid
                       LEFT JOIN field_data_field_weight     ON field_data_field_weight.entity_id = users.uid
                       LEFT JOIN field_data_field_phone_number     ON field_data_field_phone_number.entity_id = users.uid
       WHERE webform_submissions.sid= :sid", array(':sid' => $sid));

   foreach ($result as $record){
      $curr = db_query("SELECT data FROM webform_submitted_data where sid= :sid  AND cid=5 LIMIT 1", array(':sid' => $sid));
         foreach ($curr as $tid){
         $record->curriculum = taxonomy_term_load($tid->data)->name;
         }
   }
$record->html = "<div class=\"cadet\">
   <div class=\"record_checkbox cadet_row\">
   <input type=\"checkbox\" name=\"record_id\" value=\"" . $requested_date . ":" . $record->capid . "\" title=\"Send email to this cadet\">
   </div>
   <div class=\"cadet_name cadet_row\">"       . $record->lname  . ", 
                                             " . $record->fname  . "</div>
   <div class=\"cadet_capid cadet_row\">"      . $record->capid  . "</div>
   <div class=\"cadet_weight cadet_row\">"     . $record->weight . "</div>
   <div class=\"cadet_phone cadet_row\"><a href=\"tel:"    . $record->phone . "\">" . $record->phone . "</a></div>
   <div class=\"cadet_email cadet_row\"><a href=\"mailto:" . $record->mail  . "\">" . $record->mail  . "</a></div>
   <div class=\"curriculum cadet_row\">"       . $record->curriculum . "</div>
</div>";

return($record);
}

