<?php
/**
 * Return array containing the months of the year. January = 1
 */
function getMonths(){
return (array('','January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'));
}

/**
 * Return array contining the days of the week. Sunday = 1
 */
function getDays(){
return(array('', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'));
}
